### ISSUE TITLE
Instead of inputting initial basis paramaters in bparams lists, input them as part of basis function construction

### ISSUE THREAD

**Issue by dsteinberg** [NICTA/revrand#83]
i.e. right now we have something like:
```
basis = RandomRBF(Xdim=D, nbases=K) + RandomRBF_ARD(Xdim=D, nbases=K)
params = learn(X, y, basis, bparams = [1. , np.ones(D)])
```
to
```
basis = RandomRBF(Xdim=D, nbases=K, lenscale_init=1) + RandomRBF_ARD(Xdim=D, nbases=K, lenscale_init=np.ones(D))
params = learn(X, y, basis)
```
is this more intuitive? 

What about it we combine the initial values and the bounds as well?

**Comment by johnny555** [comment]
I think that this will be an improvement. 
The main benefit will be that the bparams list will no-longer be dependent upon the (potentially arbitrary) concatenation order of the basis objects.
It will also be clearer, as it will be clear exactly which basis object is receiving which parameters, and we can use keyword arguments for the initialisation (rather than unpacking a list). 
I guess the only draw back is that it makes it harder to keep changing the initial conditions for learning, perhaps making something like Cross Validation of hyper-parameters more difficult. However I doubt that the cost of over-writing the object or even just creating a new basis object for each run will outweigh the benefits from improved clarity and ease of use.

**Comment by dsteinberg** [comment]
I didn't think about cross-val, but I agree, very small cost compared to the more intuitive interface! I'll try to get onto this soon!
