### ISSUE TITLE
Variance of prediction results with BLR and GLM (and a few questions)

### ISSUE THREAD

**Issue by MushroomHunting** [NICTA/revrand#98]
Hey guys,

have a few questions regarding the BLR and GLM implementations

- Is the GLM designed to be a scalable version of BLR, or is the BLR the scalable version of GP with the use of kernel randomisation?
- Every time I use GLM and BLR on the same data, GLM seems to take a long time to converge, and I can't get it to produce results anywhere near as close as the GP and BLR do. (see image 1 of attached plots)
- Using BLR (the same happens with the GLM too), there is a very high variance of prediction results and sometimes it flat-lines (see images 2,3,4). Is this behaviour expected, if so, what would be the cause of it and how could one go about mitigating the effect?
- Regarding the BLR, do you have a technical reference I could look up to read a bit more into trying to understand the general model being used with optimisation via the ELBO?
- When adding 3+ dimensions (using BLR), I get a consistent frequent occurrence of the following error

Traceback (most recent call last):
		  File "...\site-packages\revrand-0.4.1-py3.5.egg\revrand\mathfun\linalg.py", line 114, in solve_posdef
		    L = cholesky(A, lower=lower)
		  File "...\site-packages\scipy\linalg\decomp_cholesky.py", line 81, in cholesky  check_finite=check_finite)
		  File "...\site-packages\scipy\linalg\decomp_cholesky.py", line 30, in _cholesky		    raise LinAlgError("%d-th leading minor not positive definite" % info)

Timing results for my test:
GLM =  32.92785692051233  seconds
BLR =  0.8038480074900155  seconds
GP =  1.2076108629262308  seconds

![figure_1](https://cloud.githubusercontent.com/assets/17902209/16605850/13edc0b0-4376-11e6-93c1-1dda07e7b22e.png)
![blr q3](https://cloud.githubusercontent.com/assets/17902209/16605853/13ef2144-4376-11e6-92dd-3f5e030191e2.png)
![blr q](https://cloud.githubusercontent.com/assets/17902209/16605852/13ee2708-4376-11e6-8539-9687f7bd2f7c.png)
![blr q2](https://cloud.githubusercontent.com/assets/17902209/16605851/13edf58a-4376-11e6-8200-d01a3e180b2d.png)

quick overview of settings:
kernel = combo of 3 RandomRBF with 3 different lengthscales
N = 500
Ns = 100
lenscale2 = 0.5  # For the Combo basis
lenscale3 = 2
lenscale4 = 5
noise = 0.21
rho = 0.90
passes = 70
postcomp = 10
epsilon = 1e-7
batchsize = 10
reg = 1

llhood = likelihoods.Gaussian(var_init=Parameter(noise**2, Positive()))
params_glm = glm.learn(Xtrain, ytrain, llhood, base, ..... )

cheers!
Anthony

**Comment by dsteinberg** [comment]
Hey Anthony,  thanks for giving us such thorough examples of your issues! I've been able to replicate a lot of them as well. In answer to some of you general questions:
- The BLR with appropriate basis functions is designed to be a "large scale" approximation to a GP. While it can deal with larger datasets than a GP, we are still not using SGD with it. The reason for this is that it still requires O(D^3) computations per iteration (where D is the dimensionality of the features). This is better than a GP O(N^3), but still not great for SGD which requires _a lot_ of iterations. The GLM can approximate the BLR (and by extension the GP) and can use SGD as it is O(KD) per iteration, where K is the number of mixtures to approximate the posterior with. So my recommendation is use a GP when you have a small dataset, the BLR when you have more than a few thousand points, and the GLM when you really need to scale up, or have non-Gaussian likelihoods (eg. classification).
- The GLM does need many many iterations to converge unfortunately. Such is the nature of SGD, and this GLM is a pretty darn complex model (i.e. it has a very non-convex objective). Would it be easier for you if I changed the interface such that you can choose the number of iterations for learning GLM, instead of the number of passes over the data (where iterations is a function of batch-size and dataset size)? Also, this is pretty experimental code still, and so I hope I can speed up learning in the (near) future.
- The results you get there are fairly concerning! I think the GLM just hasn't been run for enough iterations, let me know if you still get this after running the GLM for longer. The BLR on the other hand is not performing as expected. This could be for a few reasons; (1) the optimiser got stuck in a local optimum (2) you aren't using enough basis functions (though I got this behaviour on occasion even with many basis functions) (3) the ELBO objective is not performing as well as log-marginal-likelihood (LML). I'm going to take a look at this now -- I'll add in some random restarts and see if this fixes the issues above, and if not, I'll look into LML optimisation, see #99.
- I'm currently writing a report on the algorithms in this library, there is an early version of it here: https://github.com/NICTA/revrand/blob/feature/%2392/docs/report/report.pdf
- I thought I fixed that non-psd error you got here: https://github.com/NICTA/revrand/blob/master/revrand/mathfun/linalg.py#L121 but maybe not? Very strange, I'll investigate further, see #100. I've been using this library on hundreds of dimensions without an issue like this ... very odd.

Thanks again for taking the time to point out all of these issues. I'm very sorry you are having trouble with this code. It is all pretty new and experimental, and we want to use it in some production systems so feedback like this is really useful. Let me know if you have any more issues, and also, if you feel like contributing back to this code base, you would be most welcome!

**Comment by dsteinberg** [comment]
@MushroomHunting I found a pretty serious bug in `solve_posdef` that actually caused many of these issues. Grab the latest master or develop and see if this fixes some of your issues. Also, I changed the GLM code to accept number of iterations to run in SGD, rather than number of passes over the data.

**Comment by MushroomHunting** [comment]
@dsteinberg 
Hey Daniel, thanking you kindly for the detailed reply, and for the link to the report too - have just done some tests with the updates and it seems to have fixed the issues. Hopefully in the near future I'll be able to make some contributions
thanks again,
Anthony
